export const GLOBAL_ENV = {
  BACKEND_BASE_URL_API: import.meta.env.VITE_BACKEND_DOMAIN_BASE_URL_API,
  BACKEND_BASE_URL: import.meta.env.VITE_BACKEND_DOMAIN_BASE_URL,
  FRONTEDN_BASE_URL: import.meta.env.VITE_FRONTEND_DOMAIN_BASE_URL,
};
